# Sanitizers are opt-in and use separate build directories.
function(enable_sanitizers target)
  option(ENABLE_SANITIZER_ADDRESS "Enable address sanitizer" OFF)
  option(ENABLE_SANITIZER_LEAK "Enable leak sanitizer" OFF)
  option(ENABLE_SANITIZER_UNDEFINED_BEHAVIOR "Enable undefined behavior sanitizer" OFF)
  option(ENABLE_SANITIZER_THREAD "Enable thread sanitizer" OFF)
  option(ENABLE_SANITIZER_MEMORY "Enable memory sanitizer (requires instrumented dependencies)" OFF)

  set(sanitizers "")
  foreach(pair ADDRESS LEAK UNDEFINED_BEHAVIOR THREAD MEMORY)
    if(ENABLE_SANITIZER_${pair})
      if(pair STREQUAL "UNDEFINED_BEHAVIOR")
        list(APPEND sanitizers undefined)
      else()
        string(TOLOWER "${pair}" sanitizer)
        list(APPEND sanitizers "${sanitizer}")
      endif()
    endif()
  endforeach()
  if(NOT sanitizers)
    return()
  endif()
  if(ENABLE_SANITIZER_THREAD AND (ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_LEAK OR ENABLE_SANITIZER_MEMORY))
    message(FATAL_ERROR "Thread sanitizer must run separately from address/leak/memory sanitizers")
  endif()
  if(ENABLE_SANITIZER_MEMORY AND (ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_LEAK))
    message(FATAL_ERROR "Memory sanitizer cannot be combined with address/leak sanitizers")
  endif()
  if(MSVC)
    if(NOT "${sanitizers}" STREQUAL "address")
      message(FATAL_ERROR "This MSVC configuration supports only AddressSanitizer")
    endif()
    target_compile_options(${target} INTERFACE /fsanitize=address)
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    if(ENABLE_SANITIZER_MEMORY AND NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      message(FATAL_ERROR "Memory sanitizer requires Clang and instrumented dependencies")
    endif()
    list(JOIN sanitizers "," flags)
    target_compile_options(${target} INTERFACE -fsanitize=${flags} -fno-omit-frame-pointer)
    target_link_options(${target} INTERFACE -fsanitize=${flags})
  else()
    message(FATAL_ERROR "Sanitizers are not configured for this compiler")
  endif()
endfunction()
